<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Model;
use App\Models\ExclusionRequest;
use Carbon\Carbon;
use Faker\Generator as Faker;

$factory->define(ExclusionRequest::class, function (Faker $faker) {
    return [
        'status' => "approved",
        "created_at" => Carbon::now(),
        "updated_at" => Carbon::now(),
        "requested_at" => Carbon::now(),
        "responded_at" => Carbon::now(),
        "requester_note" => "Generated by factory",
        "responder_note" => "Generated by factory",
    ];
});
